name: Package Flashable Zip

on:
  workflow_dispatch:

jobs:
  package:
    name: Prepare Flashable Zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: Youffx/4.19-rosemary-kernel
          fetch-depth: 1

      - name: Download Latest Kernel Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: LandVe-RKSU.yml
          name: LandVe-Image-RKSU
          path: kernel_temp
          check_artifacts: true
          search_artifacts: true

      - name: Prepare Flash Folder
        run: |
          LOCAL_VER=$(grep "echo 'CONFIG_LOCALVERSION=" .github/workflows/LandVe-RKSU.yml | cut -d'"' -f2 | sed 's/^-//' | sed 's/\///g')
          DATE=$(date +"%Y%m%d")
          ZIP_NAME="${LOCAL_VER}-RKSU-${DATE}"
          
          cp kernel_temp/Image.gz-dtb .github/Flash/kernels/
          
          echo "ZIP_FINAL_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_FINAL_NAME }}
          path: .github/Flash/
          
